set_property IOSTANDARD LVCMOS33 [get_ports f1]
set_property IOSTANDARD LVCMOS33 [get_ports f2]
set_property IOSTANDARD LVCMOS33 [get_ports f3]
set_property IOSTANDARD LVCMOS33 [get_ports f4]
set_property IOSTANDARD LVCMOS33 [get_ports up_f1]
set_property IOSTANDARD LVCMOS33 [get_ports up_f2]
set_property IOSTANDARD LVCMOS33 [get_ports up_f3]
set_property IOSTANDARD LVCMOS33 [get_ports down_f2]
set_property IOSTANDARD LVCMOS33 [get_ports down_f3]
set_property IOSTANDARD LVCMOS33 [get_ports down_f4]

set_property PACKAGE_PIN R17 [get_ports f1]
set_property PACKAGE_PIN U20 [get_ports f2]
set_property PACKAGE_PIN R16 [get_ports f3]
set_property PACKAGE_PIN N16 [get_ports f4]
set_property PACKAGE_PIN R14 [get_ports up_f1]
set_property PACKAGE_PIN P14 [get_ports up_f2]
set_property PACKAGE_PIN L15 [get_ports up_f3]
set_property PACKAGE_PIN M15 [get_ports down_f2]
set_property PACKAGE_PIN T10 [get_ports down_f3]
set_property PACKAGE_PIN T12 [get_ports down_f4]

set_property IOSTANDARD LVCMOS33 [get_ports {displays[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displays[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displays[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displays[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]

set_property PACKAGE_PIN L16 [get_ports {displays[3]}]
set_property PACKAGE_PIN M18 [get_ports {displays[2]}]
set_property PACKAGE_PIN H17 [get_ports {displays[1]}]
set_property PACKAGE_PIN K19 [get_ports {displays[0]}]
set_property PACKAGE_PIN K14 [get_ports {leds[6]}]
set_property PACKAGE_PIN H15 [get_ports {leds[5]}]
set_property PACKAGE_PIN J18 [get_ports {leds[4]}]
set_property PACKAGE_PIN J15 [get_ports {leds[3]}]
set_property PACKAGE_PIN M17 [get_ports {leds[2]}]
set_property PACKAGE_PIN H18 [get_ports {leds[0]}]
set_property PACKAGE_PIN J16 [get_ports {leds[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN K18 [get_ports dp]
set_property PACKAGE_PIN H16 [get_ports clk]

# Constraints for SPEAKER
set_property PACKAGE_PIN G18 [get_ports {speaker}]
set_property IOSTANDARD LVCMOS33 [get_ports {speaker}]

set_property PACKAGE_PIN T14 [get_ports {sos}]
set_property IOSTANDARD LVCMOS33 [get_ports {sos}]

set_property PACKAGE_PIN Y14 [get_ports {sos_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {sos_led}]
